GestionClinic/GestionClinic/Controllers/AppointementsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionClinic;

namespace GestionClinic.Controllers
{
    public class AppointementsController : Controller
    {
        private BD_GCEntities db = new BD_GCEntities();

        // GET: Appointements
        public ActionResult Index()
        {
    
            return View(db.Appointement.ToList());
        }

        // GET: Appointements/Details/5
        public ActionResult ViewAppointment(int? id)
        {
            if (id == null)
            {
                return View();
            }
            List<Appointement> appointement = db.Appointement.Where(x=>x.patient_ID==id).ToList();
            if (appointement == null)
            {
                return View(appointement);
            }
            return View(appointement);
        }

        // GET: Appointements/Create
        public ActionResult CreateAppointment(int ? id)
        {
            ViewBag.doctor_ID = new SelectList(db.Doctor, "D_ID", "FullName");
            ViewBag.patient_ID = id.ToString();
            return View();
        }

        // POST: Appointements/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddAppointement([Bind(Include = "Ap_ID,Date,Time,patient_ID,doctor_ID")] Appointement appointement)
        {
            appointement.patient_ID = (int)Session["userId"];
            if (ModelState.IsValid)
            {
                db.Appointement.Add(appointement);
                db.SaveChanges();
                return View();
            }

           // ViewBag.doctor_ID = new SelectList(db.Doctor, "D_ID", "FullName", appointement.doctor_ID);
           // ViewBag.patient_ID = Session["userId"].ToString();
            return View("appointement failed");
        }

     

        // GET: Appointements/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appointement appointement = db.Appointement.Find(id);
            if (appointement == null)
            {
                return HttpNotFound();
            }
            return View(appointement);
        }

        // POST: Appointements/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appointement appointement = db.Appointement.Find(id);
            db.Appointement.Remove(appointement);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionClinic/GestionClinic/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionClinic;

namespace GestionClinic.Controllers
{
    public class DoctorsController : Controller
    {
        private BD_GCEntities db = new BD_GCEntities();

        // GET: Doctors
        public ActionResult Index()
        {
            return View(db.Doctor.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctor.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "D_ID,FullName,email,ContactNumber,Specialty")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctor.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctor.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "D_ID,FullName,email,ContactNumber,Specialty")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctor.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Doctor doctor = db.Doctor.Find(id);
            db.Doctor.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionClinic/GestionClinic/Controllers/FeedbacksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GestionClinic;
using GestionClinicML.Model;

namespace GestionClinic.Controllers
{
    public class FeedbacksController : Controller
    {
        private BD_GCEntities db = new BD_GCEntities();

        // GET: Feedbacks
        public ActionResult Index()
        {
            var feedback = db.Feedback.Include(f => f.Patient);
            return View(feedback.ToList());
        }

        // GET: Feedbacks/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // GET: Feedbacks/Create
        public ActionResult Create()
        { 
            Feedback f = new Feedback();
            string feedback= TempData["userFeedback"].ToString();
            ModelInput sampleData = new ModelInput()
            {
                Col0 =feedback,
            };
            f.patient_ID = Convert.ToInt32(TempData["userId"].ToString());
            f.feedback1 = TempData["userFeedback"].ToString();
            f.feedback1 = sampleData.Col0;
            var result = ConsumeModel.Predict(sampleData);
            f.result = result.Prediction;
          
           // f.result = Convert.ToString(TempData["result"]);
            return RedirectToAction("Createfeed",f);
        }

        // POST: Feedbacks/Create
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
       // [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Createfeed([Bind(Include = "patient_ID,feedback1,result")] Feedback feedback)
        {
            //feedback.patient_ID = (int)Session["userId"];


            db.Feedback.Add(feedback);

            db.SaveChanges();
           
                return RedirectToAction("PatientHome","Patients");
           
        }
        // GET: Feedbacks/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            ViewBag.patient_ID = new SelectList(db.Patient, "P_ID", "Name", feedback.patient_ID);
            return View(feedback);
        }

        // POST: Feedbacks/Edit/5
        // Pour vous protéger des attaques par survalidation, activez les propriétés spécifiques auxquelles vous souhaitez vous lier. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "patient_ID,feedback1")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Entry(feedback).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.patient_ID = new SelectList(db.Patient, "P_ID", "Name", feedback.patient_ID);
            return View(feedback);
        }

        // GET: Feedbacks/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Feedback feedback = db.Feedback.Find(id);
            if (feedback == null)
            {
                return HttpNotFound();
            }
            return View(feedback);
        }

        // POST: Feedbacks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Feedback feedback = db.Feedback.Find(id);
            db.Feedback.Remove(feedback);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GestionClinic/GestionClinic/Controllers/home1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionClinic.Controllers
{
    public class home1Controller : Controller
    {
        // GET: home1
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Index1()
        {
            return RedirectToAction("AdminLogin","Admins");
        }
        public ActionResult Index2()
        {
            return RedirectToAction("PatientLogin", "Patients");
        }
    }
}

GestionClinic/GestionClinic/Views/Doctors/Create.cshtml
@model GestionClinic.Doctor

@{
    ViewBag.Title = "Create";
}

<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <link href="~/Content/css/StyleA2.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<header>
    <h1><span>Admin</span></h1>
    <nav>
        <ul>
            <li>@Html.ActionLink("Manage doctors ", "Index", "Doctors")</li>
            <li>@Html.ActionLink(" View patients", "ViewPatients", "Patients")</li>
            <li>@Html.ActionLink(" View Appointments", "Index", "Appointements")</li>
            <li>@Html.ActionLink("Logout", "Index", "home1")</li>
        </ul>
    </nav>

</header>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Doctor</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Specialty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Specialty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Specialty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

GestionClinic/GestionClinic/Views/Doctors/Delete.cshtml
@model GestionClinic.Doctor

@{
    ViewBag.Title = "Delete";
}

<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <link href="~/Content/css/StyleA2.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<header>
    <h1><span>Admin</span></h1>
    <nav>
        <ul>
            <li>@Html.ActionLink("Manage doctors ", "Index", "Doctors")</li>
            <li>@Html.ActionLink(" View patients", "ViewPatients", "Patients")</li>
            <li>@Html.ActionLink(" View Appointments", "Index", "Appointements")</li>
            <li>@Html.ActionLink("Logout", "Index", "home1")</li>
        </ul>
    </nav>

</header>
<body>
    <h2>Delete</h2>

    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Doctor</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Specialty)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Specialty)
            </dd>

        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
    </body>
</html>

GestionClinic/GestionClinic/Views/Doctors/Details.cshtml
@model GestionClinic.Doctor

@{
    ViewBag.Title = "Details";
}
<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <link href="~/Content/css/StyleA2.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<header>
    <h1><span>Admin</span></h1>
    <nav>
        <ul>
            <li>@Html.ActionLink("Manage doctors ", "Index", "Doctors")</li>
            <li>@Html.ActionLink(" View patients", "ViewPatients", "Patients")</li>
            <li>@Html.ActionLink(" View Appointments", "Index", "Appointements")</li>
            <li>@Html.ActionLink("Logout", "Index", "home1")</li>
        </ul>
    </nav>

</header>
<body>


    <div>
        <h4>Doctor</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FullName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.FullName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.email)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ContactNumber)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Specialty)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Specialty)
            </dd>

        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.D_ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
    </body>
</html>

GestionClinic/GestionClinic/Views/Doctors/Edit.cshtml
@model GestionClinic.Doctor

@{
    ViewBag.Title = "Edit";
}
<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <link href="~/Content/css/StyleA2.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<header>
    <h1><span>Admin</span></h1>
    <nav>
        <ul>
            <li>@Html.ActionLink("Manage doctors ", "Index", "Doctors")</li>
            <li>@Html.ActionLink(" View patients", "ViewPatients", "Patients")</li>
            <li>@Html.ActionLink(" View Appointments", "Index", "Appointements")</li>
            <li>@Html.ActionLink("Logout", "Index", "home1")</li>
        </ul>
    </nav>

</header>
<body>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Doctor</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.D_ID)

            <div class="form-group">
                @Html.LabelFor(model => model.FullName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FullName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FullName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ContactNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ContactNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ContactNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Specialty, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Specialty, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Specialty, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
    </body>
</html>

GestionClinic/GestionClinic/Views/Doctors/Index.cshtml
@model IEnumerable<GestionClinic.Doctor>

@{
    ViewBag.Title = "Index";
}

<!DOCTYPE html>
<html>
<head>
    <title>Admin</title>
    <link href="~/Content/css/StyleA2.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Open+Sans:wght@300&display=swap" rel="stylesheet">
</head>

<header>
    <h1><span>Admin</span></h1>
    <nav>
        <ul>
           
                <li>@Html.ActionLink("View feedbacks ", "Index", "Feedbacks")</li>
                <li>@Html.ActionLink("Manage doctors ", "Index", "Doctors")</li>
                <li>@Html.ActionLink(" View patients", "ViewPatients", "Patients")</li>
                <li>@Html.ActionLink(" View Appointments", "Index", "Appointements")</li>
                <li>@Html.ActionLink("Logout", "Index", "home1")</li>
           
        </ul>
    </nav>

</header>
<body>
    <p><h4>Doctors List:</h4></p>
    <p>
        @Html.ActionLink("Add new doctor", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ContactNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Specialty)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContactNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Specialty)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.D_ID }) |
                    @Html.ActionLink("Details", "Details", new { id = item.D_ID }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.D_ID })
                </td>
            </tr>
        }

    </table>
</body>
</html>